services:
  frontend:
    image: node:lts-bookworm-slim
    ports:
      - 5173:5173
      - 6006:6006
    stop_grace_period: 3s
    tty: true
    volumes:
      - ./:/home/node/app/
    working_dir: /home/node/app
